# Generated by Django 3.1.4 on 2021-01-02 03:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_ems', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Departments',
            new_name='Department',
        ),
    ]
