# Generated by Django 3.1.4 on 2021-01-02 04:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_ems', '0002_auto_20210102_0311'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='departments',
            field=models.ManyToManyField(related_name='departments', through='app_ems.DeptEmp', to='app_ems.Department'),
        ),
    ]
