# Generated by Django 3.1.4 on 2021-01-02 05:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_ems', '0004_auto_20210102_0446'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='salary',
            options={'verbose_name_plural': 'salaries'},
        ),
    ]
