# Generated by Django 3.1.4 on 2021-01-03 01:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_ems', '0005_auto_20210102_0521'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Titles',
            new_name='Title',
        ),
        migrations.AlterModelOptions(
            name='deptemp',
            options={'verbose_name': 'Employee Department'},
        ),
        migrations.AlterModelOptions(
            name='deptmanager',
            options={'verbose_name': 'Manager Department'},
        ),
        migrations.AlterModelOptions(
            name='title',
            options={'verbose_name_plural': 'titles'},
        ),
    ]
