# Generated by Django 3.1.4 on 2020-12-31 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_feedback', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='feedback',
            old_name='create_on',
            new_name='created_on',
        ),
        migrations.AlterField(
            model_name='feedback',
            name='category',
            field=models.CharField(choices=[('1', 'General'), ('2', 'Management'), ('3', 'Compensation'), ('4', 'Suggestions'), ('5', 'Complaint')], default='1', max_length=10),
        ),
    ]
