# Generated by Django 3.1.4 on 2021-01-01 06:29

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_feedback', '0002_auto_20201231_1226'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feedback',
            name='email',
            field=models.CharField(max_length=150, validators=[django.core.validators.EmailValidator(), django.core.validators.MinLengthValidator(6), django.core.validators.MaxLengthValidator(100)]),
        ),
    ]
