# Generated by Django 3.1.4 on 2021-01-01 07:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_feedback', '0004_auto_20210101_0643'),
    ]

    operations = [
        migrations.AddField(
            model_name='feedback',
            name='emp_no',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
